### ISSUE TITLE
"job-dsl" directory name clashes with jenkins-cli.jar plugin installation

### ISSUE THREAD

**Issue by hoxu** [solita/solita-cd#1]
The docs instruct using `job-dsl` directory:

http://solita-cd.readthedocs.org/en/latest/solita.jenkins.html#jobs-and-views

However, it seems `jenkins-cli.jar` used by `geerlingguy.jenkins` role uses the `job-dsl` plugin name as a temporary filename, resulting in an exception:

```
TASK: [geerlingguy.jenkins | Install Jenkins plugins.] ************************
failed: [vagrant] => (item=job-dsl) => {"changed": true, "cmd": ["java", "-jar", "/opt/jenkins-cli.jar", "-s", "http://localhost:8080/", "install-plugin", "job-dsl"], "delta": "0:00:02.031533", "end": "2016-01-25 12:59:11.825503", "item": "job-dsl", "rc": 255, "start": "2016-01-25 12:59:09.793970", "warnings": []}
stderr: Unexpected exception occurred while performing install-plugin command!
java.io.IOException: Failed to copy job-dsl to /var/lib/jenkins/plugins/job-dsl.jpi
        at hudson.FilePath.copyTo(FilePath.java:1990)
        at hudson.cli.InstallPluginCommand.run(InstallPluginCommand.java:85)
        at hudson.cli.CLICommand.main(CLICommand.java:238)
        at hudson.cli.CliManagerImpl.main(CliManagerImpl.java:92)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:608)
        at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:583)
        at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:542)
        at hudson.remoting.UserRequest.perform(UserRequest.java:120)
        at hudson.remoting.UserRequest.perform(UserRequest.java:48)
        at hudson.remoting.Request$2.run(Request.java:326)
        at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
        at hudson.cli.CliManagerImpl$1.call(CliManagerImpl.java:63)
        at hudson.remoting.CallableDecoratorAdapter.call(CallableDecoratorAdapter.java:18)
        at hudson.remoting.CallableDecoratorList$1.call(CallableDecoratorList.java:21)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: remote file operation failed: job-dsl at hudson.remoting.Channel@34455f88:CLI channel from /127.0.0.1: java.io.FileNotFoundException: job-dsl (Is a directory)
        at hudson.FilePath.act(FilePath.java:986)
        at hudson.FilePath.act(FilePath.java:968)
        at hudson.FilePath.copyTo(FilePath.java:2011)
        at hudson.FilePath.copyTo(FilePath.java:1985)
        ... 22 more
Caused by: java.io.FileNotFoundException: job-dsl (Is a directory)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:146)
        at hudson.FilePath$41.invoke(FilePath.java:2016)
        at hudson.FilePath$41.invoke(FilePath.java:2011)
        at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2719)
        at hudson.remoting.UserRequest.perform(UserRequest.java:120)
        at hudson.remoting.UserRequest.perform(UserRequest.java:48)
        at hudson.remoting.Request$2.run(Request.java:326)
        at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
        at ......remote call to CLI channel from /127.0.0.1(Native Method)
        at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1416)
        at hudson.remoting.UserResponse.retrieve(UserRequest.java:220)
        at hudson.remoting.Channel.call(Channel.java:781)
        at hudson.FilePath.act(FilePath.java:979)
        ... 25 more
stdout: Installing a plugin from local file: job-dsl
```

As a result, `/var/lib/jenkins/plugins/job-dsl.jpi` ends up being an empty file, and the plugin installation request is ignored on further runs.

**Comment by sirkkalap** [comment]
Unfortunately I did not have this issue when I ran the tutorial, or maybe I was not paying attention enough. @noidi is on holiday, so we might better wait until next Monday to see this resolved.

**Comment by hoxu** [comment]
The actual error is in upstream `jenkins-cli.jar` in my opinion - it should use `/tmp` or `TMPDIR` environment variable for storing temporary files.

**Comment by noidi** [comment]
This indeed looks like an upstream problem. `jenkins-cli.jar`'s `install-plugin` command fails if the working directory contains a directory with the same name as the plugin to be installed.

```
(ansible-1.9-env) vagrant@vagrant-ubuntu-trusty-64:/tmp$ mkdir timestamper
(ansible-1.9-env) vagrant@vagrant-ubuntu-trusty-64:/tmp$ java -jar /opt/jenkins-cli.jar -s http://localhost:8080/ install-plugin timestamper
[WARN] Failed to authenticate with your SSH keys. Proceeding as anonymous
Installing a plugin from local file: timestamper
Unexpected exception occurred while performing install-plugin command!
java.io.IOException: Failed to copy timestamper to /var/lib/jenkins/plugins/timestamper.jpi
        at hudson.FilePath.copyTo(FilePath.java:1990)
        at hudson.cli.InstallPluginCommand.run(InstallPluginCommand.java:85)
        at hudson.cli.CLICommand.main(CLICommand.java:238)
        at hudson.cli.CliManagerImpl.main(CliManagerImpl.java:92)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:608)
        at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:583)
        at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:542)
        at hudson.remoting.UserRequest.perform(UserRequest.java:120)
        at hudson.remoting.UserRequest.perform(UserRequest.java:48)
        at hudson.remoting.Request$2.run(Request.java:326)
        at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
        at hudson.cli.CliManagerImpl$1.call(CliManagerImpl.java:63)
        at hudson.remoting.CallableDecoratorAdapter.call(CallableDecoratorAdapter.java:18)
        at hudson.remoting.CallableDecoratorList$1.call(CallableDecoratorList.java:21)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: remote file operation failed: timestamper at hudson.remoting.Channel@53e0510b:CLI channel from /127.0.0.1: java.io.FileNotFound
Exception: timestamper (Is a directory)
        at hudson.FilePath.act(FilePath.java:986)
        at hudson.FilePath.act(FilePath.java:968)
        at hudson.FilePath.copyTo(FilePath.java:2011)
        at hudson.FilePath.copyTo(FilePath.java:1985)
        ... 22 more
Caused by: java.io.FileNotFoundException: timestamper (Is a directory)
```

**Comment by hoxu** [comment]
Reported upstream: https://issues.jenkins-ci.org/browse/JENKINS-32705

**Comment by noidi** [comment]
Reopened until we have a workaround or the issue is fixed upstream.

**Comment by hoxu** [comment]
Fixed by workaround in:
https://github.com/solita/ansible-role-solita.jenkins/commit/b69f826cc376b565e39f0d5cdb296c8198dc8c63
